### ISSUE TITLE
Duplicate entry '252-wgevents-default-wgevents_admin_maintenance.tpl-admin'

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/wgevents#12]
During fresh installation:

```
0.000200 - INSERT INTO tplfile (tpl_id, tpl_module, tpl_refid, tpl_tplset, tpl_file, tpl_desc, tpl_lastmodified, tpl_lastimported, tpl_type) VALUES (0, 'wgevents', 252, 'default', 'wgevents_admin_maintenance.tpl', '', 1644225210, 1644225210, 'admin')
Error number: 1062
Error message: Duplicate entry '252-wgevents-default-wgevents_admin_maintenance.tpl-admin' for key 'tpl_refid_module_set_file_type'
```

Also: 
`Error: Error: Call to a member function getVar() on bool in file /class/libraries/vendor/xoops/xmf/src/Module/Helper/GenericHelper.php line 168`

I'm not sure if both are related or not. 

But module does install...

**Comment by ggoffy** [comment]
I have only the second error, but as far as I see I have included the autoloader everywhere.
Do you see where the problem is?

**Comment by mambax7** [comment]
You had twice the same template in xoops_version.php:

`    ['file' => 'wgevents_admin_maintenance.tpl', 'description' => '', 'type' => 'admin'],`

**Comment by mambax7** [comment]
Regarding the 2nd error, the issue is that you ask the helper to "getConfig" before the installation is completed (in menu.php, line 83):

```php
if ((bool)$helper->getConfig('use_history')) {
    $adminmenu[] = [
        'title' => \_MI_WGEVENTS_ADMENU11,
        'link' => 'admin/registrationshist.php',
        'icon' => 'assets/icons/32/registrationshist.png',
    ];
    $adminmenu[] = [
        'title' => \_MI_WGEVENTS_ADMENU12,
        'link' => 'admin/answershist.php',
        'icon' => 'assets/icons/32/answershist.png',
    ];
}
```

I had the same issue in my modules in menu.php, so what I'm doing now is to check first if the Module is already installed and available to the Helper:

```php
if (is_object($helper->getModule()) && false !== $helper->getModule()->getInfo('modicons32')) {
    $pathModIcon32 = $helper->url($helper->getModule()->getInfo('modicons32'));
}
```
