### ISSUE TITLE
possibility to delete the module folder in uploads as user

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wgevents#35]
Can you add the possibility to delete module's folder in /uploads when I uninstall the module?
I have to log in as administrator on the ftp to delete it.

![image](https://user-images.githubusercontent.com/4613970/171075656-f032db10-37b7-4449-b2cb-151e9d93447a.png)

I've tested Heyula's module and it works with his module:
https://github.com/Heyula/testimonial

**Comment by ggoffy** [comment]
hi. it was the wish of Alain (I think) to delete the folder not when uninstalling a module

https://github.com/XoopsModules25x/wgblocks/issues/9

In the module itself I can solve it only in one way (always deleting or always renaming). To give you the choice we have to change the XOOPS core

**Comment by cesagonchu** [comment]
Yes, it's fine to rename it, but I would like to be able to go on my ftp as a user to delete it.

**Comment by montuy337513** [comment]
Hello,
I think Cesag wants that when the module is uninstalled, all directories installed in /uloads by the module are removed.

**Comment by montuy337513** [comment]
I understand, it is sometimes difficult to satisfy everyone.
In principle, when I delete a module, I also want the data to be deleted. Basically, I don't need it anymore.
And using Filezilla to clean up makes deleting complicated.
I don't know your mod. But here, I will add the possibility of copying the data by renaming the directory in a "maintenance" tab.
And when we delete the module, we delete all the data, including in /uploads

**Comment by mambax7** [comment]
Maybe the easiest way would be to add a question during the "module uninstall process":

"You have data in the /upload folder. Would you like to delete it or rename the folder?
[Delete]  [Rename]

This way the user can decide.

**Comment by ggoffy** [comment]
@montuy337513 : I agree with you, when I uninstall a module I want also clean up upload folder
@mambax7 : To give you the choice we have to change the XOOPS core. should I create an issue on https://github.com/XOOPS/XoopsCore25/issues ?

**Comment by mambax7** [comment]
The easiest way is to do it in the module, as I don't think that Richard will have the time to do it. 
But you can create an issue as an "Enhancement" for consideration in future release

**Comment by ggoffy** [comment]
> The easiest way is to do it in the module

is there somewhere an example?

**Comment by mambax7** [comment]
You could probably use the "pre-uninstall" function in the uninstall.php. 

```php
/**
 * Prepares system prior to attempting to uninstall module
 * @param \XoopsModule $module {@link XoopsModule}
 *
 * @return bool true if ready to uninstall, false if not
 */
function xoops_module_pre_uninstall_wgevents(\XoopsModule $module): bool
{
    // either ask the user here, or check in the settings, and delete or rename the folder
    return true;
}
```
I didn't test it, but I hope that it would work here...

**Comment by ggoffy** [comment]
as far as I see: the  pre_uninstall function can execute some code, but i can not handle a confirm form, but I will test it and report the result

**Comment by cesagonchu** [comment]
Thank you for trying to solve the problem.
There is no rush.
Again, your idea of renaming the folder in "uploads" is an ingenious idea.
Mamba's proposal to give the user the choice in the module Preferences is very good.
If I ask to be able to delete in the "uploads" folder, it's because I think about the users who are on a shared server.
They are often limited by the size of the files on their FTP.

**Comment by cesagonchu** [comment]
After some tests, I found out that I can delete the module folder in "uploads" only when I create "events" manually.
However, when I import data with the "Import Sample Data (will delete ALL current data)" button, I cannot delete the folder in "uploads" anymore.

**Comment by ggoffy** [comment]
it is as I was thinking:
![grafik](https://user-images.githubusercontent.com/7547661/171176171-6afd3e09-8ef1-4cdb-b448-9c2d847afb18.png)

the core is going through xoops_module_pre_uninstall_wgevents:

- if there is a xoops_confirm it will be ignored, as it is only an output via echo
- if xoops_module_pre_uninstall_wgevents returns true, the process will be finished
- if xoops_module_pre_uninstall_wgevents returns false, the whole uninstalling process will be stopped with an error notice

therefore I suggest following:

- during uninstall procedure the uploads directory should be cleaned up and folders/files of the module should be deleted
- if someone wants to save the data it must be done manually or the function of "Export Tables to YAML" must be used, because this function creates also a copy of existing upload folder in test folder

is this ok for everyone?

**Comment by montuy337513** [comment]
> during uninstall procedure the uploads directory should be cleaned up and folders/files of the module should be deleted
if someone wants to save the data it must be done manually or the function of "Export Tables to YAML" must be used, because this function creates also a copy of existing upload folder in test folder

this corresponds to normal operation for me, so OK
