### ISSUE TITLE
Error when submitting an event

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/wgevents#4]
```
0.001086 - INSERT INTO `wgevents_events` (`ev_catid`, `ev_name`, `ev_logo`, `ev_desc`, `ev_datefrom`, `ev_dateto`, `ev_contact`, `ev_email`, `ev_location`, `ev_locgmlat`, `ev_locgmlon`, `ev_locgmzoom`, `ev_fee`, `ev_register_use`, `ev_status`, `ev_galid`, `ev_datecreated`, `ev_submitter`) VALUES (1,'nthnhnth','blank.gif','nthnthnthnthnh',1643270400,1643270400,'nthnthnhnth','','ssssss',0,0,0,0,0,5,0,1643270407,1)
Error number: 1054
Error message: Unknown column 'ev_catid' in 'field list'
```

**Comment by ggoffy** [comment]
can you check the table in the database, maybe something went wrong when installing the module
 
it should be there, because it is in the definition in mysql.sql

**Comment by mambax7** [comment]
In the wgevents_events table I have only one field: ev_submitter

![image](https://user-images.githubusercontent.com/613686/151318584-fbca043b-fdc1-4aeb-874e-0a47c383f35a.png)

**Comment by ggoffy** [comment]
are you testing with 8.1 ? I developed with 8.0 and current xoopscore and it works fine

**Comment by mambax7** [comment]
I was testing on 7.4.27

I reinstalled, and the fields are there now.

**Comment by ggoffy** [comment]
ok, fine
I retested also with 7.4.0, no problem
